# Generated by Django 2.2.4 on 2019-08-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='descricao',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
