# Generated by Django 2.2.4 on 2019-08-18 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_banda_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField(max_length=364)),

            ],
        ),
        migrations.AddField(
            model_name='banda',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]



# class Image(models.Model):
#     name= models.CharField(max_length=500)
#     videofile= models.FileField(upload_to='images/', null=True, verbose_name="")

#     def __str__(self):
#         return self.name + ": " + str(self.imagefile)