# Generated by Django 2.2.4 on 2019-08-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190817_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almossom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Perfil_Info',
            new_name='Perfil',
        ),
        migrations.CreateModel(
            name='ProgramacaoAlmossom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('almossom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Almossom')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Banda')),
            ],
        ),
        migrations.AddField(
            model_name='almossom',
            name='bandas',
            field=models.ManyToManyField(through='main.ProgramacaoAlmossom', to='main.Banda'),
        ),
    ]
