# Generated by Django 2.2.4 on 2019-09-12 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190911_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, upload_to='static/events_pics')),
            ],
        ),
        migrations.AlterField(
            model_name='almossom',
            name='bandas',
            field=models.ManyToManyField(through='main.ProgramacaoAlmossom', to='main.Banda'),
        ),
        migrations.AlterField(
            model_name='programacaoalmossom',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Banda'),
        ),
    ]
